---
- name: "First Playbook"
  hosts: routers
  connection: network_cli
  gather_facts: no
  tasks: 
    - name: "Task to get router interface output"
      ios_command:
        commands: "show ip interface brief"
      register : cli_result

    - name: "Create output directory"
      file:
        path: "outputs"
        state: directory
      run_once: True

    - name: "Save output to directory"
      copy:
        content: "{{ cli_result.stdout[0] }}\n"
        dest: "outputs/{{ inventory_hostname }}.txt" 
 
    - name: "Configure loopback interfaces"
      ios_config:
        lines:
          -  "ip address {{ item.int_addr }} 255.255.255.255"
        parents: "interface {{ item.int_name }}"
      with_items: "{{ interfaces }}"

    - name: "Create configs directory"
      file:
        path: "configs"
        state: directory
      run_once: True
        
    - name: "Create BGP config"
      template:
        src: "{{ ansible_network_os }}_bgp.j2"
        dest: "configs/{{ inventory_hostname }}_bgp.config"
 
    - name: "Create routes config"
      template:
        src: "{{ ansible_network_os }}_routes.j2"
        dest: "configs/{{inventory_hostname }}_routes.config"

    - name: "Configure routes"
      ios_config:
        src: "configs/{{ inventory_hostname }}_routes.config"
      register: route_add 
      
    - name: "Configure BGP"
      ios_config:
        src: "configs/{{ inventory_hostname }}_bgp.config"
      register: updates

  
     
    - name: "Task to get bgp output"
      ios_command:
        commands: "show ip bgp summary"
#        wait_for: result['stdout_lines'][0] contains Established
      register: bgp_output

    - name: "Print router bgp output"
      debug:
        msg: "{{ bgp_output.stdout_lines[0][-3:-1] }}"
        

- name: "Linux Playbook"
  hosts: linux
  become: true
  become_user: root
#  connection: linux
  tasks:
    - name: "Task to print current working directory"
      shell: "pwd"
      register: linux_result
 
    - name: "Print directory"
      debug:
        msg: "{{ linux_result.stdout }}"

    - name: "Checking and Installing update"
      apt:       
        name: "*"
        state: latest

    - name: "Remove wget"
      apt:
        name: wget
        state: absent
