---
ansible_host: "100.10.1.6"
asn: "30"

interface:
  - int_name: "Loopback1"
    int_addr: "3.3.3.3"
  - int_name: "Loopback2"
    int_addr: "30.30.30.30"
    
ansible_httpapi_use_ssl: "yes"
ansible_httpapi_validate_certs: "no"
ansible_httpapi_port: "443"
    
  
