---
ansible_host: "100.10.1.4"
asn: "10"

interfaces:
  - int_name: "Loopback1"
    int_addr: "1.1.1.1"
  - int_name: "Loopback2"
    int_addr: "10.10.10.10"
    
bgp:
  asn: "10"
  neighbors:
    - address: "192.168.10.2"
      remote_as: "20"
    - address: "192.168.20.3"
      remote_as: "30"
  networks:
    - address: "10.10.10.10"
      mask : "255.255.255.255"
   

