---
ansible_host: "192.168.122.174"
asn: "10"

interfaces:
  - int_name: "Loopback1"
    int_addr: "1.1.1.1"
  - int_name: "Loopback2"
    int_addr: "10.10.10.10"
    
bgp:
  asn: "10"
  neighbors:
    - address: "2.2.2.2"
      remote_as: "20"
      next_hop: "192.168.122.193"
    - address: "3.3.3.3"
      remote_as: "30"
      next_hop: "1.2.3.4"
  source: "Loopback1"
  networks:
    - address: "10.10.10.10"
      mask : "255.255.255.255"
   

