---
ansible_host: "100.10.1.5"
asn: "20"

interfaces:
  - int_name: "Loopback1"
    int_addr: "2.2.2.2"
  - int_name: "Loopback2"
    int_addr: "20.20.20.20"
    
    
bgp:
  asn: "20"
  neighbors:
    - address: "192.168.10.1"
      remote_as: "10"
    - address: "192.168.20.3"
      remote_as: "30"
  networks:
    - address: "20.20.20.20"
      mask : "255.255.255.255"

