---
ansible_host: "100.10.1.5"
asn: "20"

interfaces:
  - int_name: "Loopback1"
    int_addr: "2.2.2.2"
  - int_name: "Loopback2"
    int_addr: "20.20.20.20"
    
    
bgp:
  asn: "20"
  neighbors:
    - address: "1.1.1.1"
      remote_as: "10"
      next_hop: "192.168.122.174"
    - address: "3.3.3.3"
      remote_as: "30"
      next_hop: "5.6.7.8"
  source: "Loopback1"
  networks:
    - address: "20.20.20.20"
      mask : "255.255.255.255"

