---
ansible_host: "192.168.122.193"
asn: "20"

interfaces:
  - int_name: "Loopback1"
    int_addr: "2.2.2.2"
  - int_name: "Loopback2"
    int_addr: "20.20.20.20"
    
    
bgp:
  asn: "20"
  neighbors:
    - address: "1.1.1.1"
      remote-as: "10"
    - address: "3.3.3.3"
      remote-as: "30"
  source: "2.2.2.2"
  networks:
    - address: "20.20.20.20"
      mask : "255.255.255.255"

